version: '3.8'
services:
  db:
    image: postgres:13.6-alpine3.15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cards_api
  api:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
